[browser]
gatherUsageStats = false

[client]
showErrorDetails = false

[server]
headless = true

[theme]
base = "light"
primaryColor = "#22C7D6"
backgroundColor = "#F4F7F9"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#16222D"
font = "sans serif"
